### ISSUE TITLE
Error in server

### ISSUE THREAD

**Issue by lalitoego** [DoctorFTB/StoneChest#5]
Loading the Stone Chest 1.16.1 1.0.0 version into my 1.16.1 server, launched the following error [modloader-worker-0/ERROR]

**Comment by lalitoego** [comment]
This is the whole line

[18:10:03] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID:
 stonechest, class ftblag.stonechest.StoneChest
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: ftblag.stonechest.SCEventHandler.onTextureStitch(Lnet/
minecraftforge/client/event/TextureStitchEvent$Pre;)V
        at ftblag.stonechest.SCEventHandler.init(SCEventHandler.java:31) ~[?:1.0.0] {re:classloading,pl:runtimedist
cleaner:A}
        at ftblag.stonechest.StoneChest.<init>(StoneChest.java:20) ~[?:1.0.0] {re:classloading}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_252] {}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_2
52] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?
:1.8.0_252] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_252] {}
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_252] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:32.0] {re:c
lassloading}
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_252] {}
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_252] {}
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:1.8.0_252] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_252] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_252] {}
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) [?:1.8.0_252] {}
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_252] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252] {}
Caused by: java.lang.NoSuchMethodError: ftblag.stonechest.SCEventHandler.onTextureStitch(Lnet/minecraftforge/client

**Comment by DoctorFTB** [comment]
Hello. Check 1.0.1 version.

**Comment by lalitoego** [comment]
Yeeeah. It works now
